#!/bin/sh
echo "Informe a versão (enter para \"latest\")"
read version
if [ -z $version ]; then
  version=latest
fi
echo "Executando o comando: docker image build -t debian-base:$version"
docker image build -t debian-base:$version .
